
include: package:flutter_lints/flutter.yaml

linter:
  rules:
  - require_trailing_commas
  - prefer_const_declarations
  - unnecessary_this
  - prefer_final_locals
  - omit_local_variable_types    
  - unawaited_futures
  - discarded_futures
  - prefer_expression_function_bodies
  - always_specify_types: false

analyzer:
  language:
    # these can be turned on
    # strict-inference: true
    strict-raw-types: true
  errors:
    ambiguous_import: error
    unused_import: error
    always_use_package_imports: error
    directives_ordering: error
    require_trailing_commas: error
    unused_element: error
    prefer_single_quotes: error
    prefer_const_declarations: error
    unnecessary_this: error
    prefer_final_locals: error
    unnecessary_library_name: error
    duplicate_import: error
    omit_local_variable_types: error
    dead_code: error
    use_function_type_syntax_for_parameters: error
    avoid_shadowing_type_parameters: error
    constant_pattern_never_matches_value_type: error
    annotate_overrides: error
    use_super_parameters: error
    body_might_complete_normally_nullable: error
    dead_null_aware_expression: error
    unused_local_variable: error
    unnecessary_import: error
    unnecessary_late: error
    unnecessary_null_comparison: error
    unnecessary_non_null_assertion: error
    unnecessary_const: error
    no_leading_underscores_for_local_identifiers: error
    invalid_null_aware_operator: error
    pattern_never_matches_value_type: error
    unnecessary_to_list_in_spreads: error
    collection_methods_unrelated_type: error
    unreachable_switch_case: error
    strict_raw_type: error
    prefer_is_empty: error
    null_check_on_nullable_type_parameter: error
    unused_field: error
    always_specify_types: error
    prefer_final_fields: error
    sort_child_properties_last: error

    avoid_unnecessary_containers: warning
    unawaited_futures: warning
    discarded_futures: warning
    unnecessary_cast: warning
    deprecated_member_use: warning
    deprecated_member_use_from_same_package: warning
    use_build_context_synchronously: warning
    use_key_in_widget_constructors: warning
    prefer_expression_function_bodies: warning

    depend_on_referenced_packages: ignore
    curly_braces_in_flow_control_structures: ignore